- id: cs2_bridge_apply_led_packages_state_on_change
  alias: CS2 Bridge - Apply LED Packages State on Change
  trigger:
    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
      id: hard_reset

    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_win_team
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_winner
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_state_round_win_team
      id: normal_refresh

  action:
    - choose:
        - conditions:
            - condition: trigger
              id: hard_reset
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_led_packages
                  - script.cs2_bridge_low_hp_team_breath_led_packages
                  - script.cs2_bridge_critical_hp_red_breath_led_packages
                  - script.cs2_bridge_burning_flicker_led_packages
            - delay:
                milliseconds: 150
            - service: light.turn_on
              target:
                entity_id: light.cs2gsi
              data:
                brightness_pct: >
                  {% if states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase') == 'freezetime' %}
                    100
                  {% else %}
                    35
                  {% endif %}
                hs_color: >
                  {% if states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team') == 'CT' %}
                    [240, 100]
                  {% elif states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team') == 'T' %}
                    [120, 100]
                  {% else %}
                    [0, 0]
                  {% endif %}
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_apply_led_packages_state

      default:
        - service: script.turn_on
          target:
            entity_id: script.cs2_bridge_apply_led_packages_state
  mode: restart

- id: cs2_bridge_bombtimer_einzig_led_packages
  alias: CS2 Bridge - Bombtimer einzig LED Packages
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
              above: 0
          sequence:
            - stop: Flash overlay aktiv

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
              state: "blink"
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
              state: "red"
            - condition: state
              entity_id: binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
              state: "off"
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_led_packages
                  - script.cs2_bridge_apply_led_packages_state
                  - script.cs2_bridge_low_hp_team_breath_led_packages
                  - script.cs2_bridge_critical_hp_red_breath_led_packages
                  - script.cs2_bridge_burning_flicker_led_packages
            - service: light.turn_on
              target:
                entity_id: light.cs2gsi
              data:
                brightness_pct: 100
                rgb_color: [255, 0, 0]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
              state: "blink"
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
              state: "red"
            - condition: state
              entity_id: binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
              state: "on"
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_led_packages
                  - script.cs2_bridge_apply_led_packages_state
                  - script.cs2_bridge_low_hp_team_breath_led_packages
                  - script.cs2_bridge_critical_hp_red_breath_led_packages
                  - script.cs2_bridge_burning_flicker_led_packages
            - service: light.turn_off
              target:
                entity_id: light.cs2gsi

      default:
        - stop: Nicht im Bombtimer-Modus
  mode: restart

- id: cs2_bridge_bomb_exploded_rot_kurz_led_packages
  alias: CS2 Bridge - Bomb exploded rot kurz LED Packages
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
      to: "exploded"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages
          - script.cs2_bridge_burning_flicker_led_packages

    - service: light.turn_on
      target:
        entity_id: light.cs2gsi
      data:
        brightness_pct: 100
        rgb_color: [255, 0, 0]

    - wait_for_trigger:
        - platform: state
          entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase
          to: "freezetime"
      timeout: "00:01:00"
      continue_on_timeout: true

    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_led_packages
  mode: restart

- id: cs2_bridge_bomb_defused_blau_blinken_led_packages
  alias: CS2 Bridge - Bomb defused blau blinken LED Packages
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
      to: "defused"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages
          - script.cs2_bridge_burning_flicker_led_packages
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_defused_blue_blink_led_packages
  mode: restart

- id: cs2_bridge_burning_start_led_packages
  alias: CS2 Bridge - Burning Start LED Packages
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      above: 0
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_restore_context_led_packages
          - script.cs2_bridge_apply_led_packages_state
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages

    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_burning_flicker_led_packages
  mode: restart

- id: cs2_bridge_burning_ende_led_packages
  alias: CS2 Bridge - Burning Ende LED Packages
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      below: 1
  action:
    - service: script.turn_off
      target:
        entity_id: script.cs2_bridge_burning_flicker_led_packages

    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_led_packages
  mode: restart

- id: cs2_bridge_flashed_kurzer_flash_led_packages
  alias: CS2 Bridge - Flashed kurzer Flash LED Packages
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
      above: 0
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages
          - script.cs2_bridge_burning_flicker_led_packages
          - script.cs2_bridge_restore_context_led_packages
    - service: light.turn_on
      target:
        entity_id: light.cs2gsi
      data:
        brightness_pct: 100
        color_temp_kelvin: 6500
    - delay:
        milliseconds: 1400
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
          below: 1
      timeout: "00:00:02"
      continue_on_timeout: true
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_led_packages
  mode: restart

- id: cs2_bridge_low_hp_controller_led_packages
  alias: CS2 Bridge - Low HP Controller LED Packages
  trigger:
    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages

    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode') | lower in ['blink']
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb') | lower in ['exploded', 'defused']
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed') | float(0) > 0
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning') | float(0) > 0
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked') | float(0) > 0 }}
          sequence:
            - stop: Higher priority active

        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              above: 0
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 16
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_critical_hp_red_breath_led_packages

        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              above: 15
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 30
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_low_hp_team_breath_led_packages

      default:
        - service: script.turn_on
          target:
            entity_id: script.cs2_bridge_apply_led_packages_state
  mode: restart

- id: cs2_bridge_damage_kurzer_boost_led_packages
  alias: CS2 Bridge - Damage kurzer Boost LED Packages
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state is not none
           and trigger.to_state is not none
           and trigger.from_state.state not in ['unknown','unavailable','none','None','']
           and trigger.to_state.state not in ['unknown','unavailable','none','None','']
           and (trigger.to_state.state | int(0)) < (trigger.from_state.state | int(0))
           and (trigger.to_state.state | int(0)) > 0 }}
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode') | lower not in ['blink'] }}"
    - condition: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
      below: 1
    - condition: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      below: 1
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb') | lower not in ['exploded', 'defused'] }}"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_restore_context_led_packages
          - script.cs2_bridge_low_hp_team_breath_led_packages
          - script.cs2_bridge_critical_hp_red_breath_led_packages

    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 16
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cs2gsi
              data:
                brightness_pct: 100
                hs_color: [0, 100]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
              state: "CT"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cs2gsi
              data:
                brightness_pct: 100
                hs_color: [240, 100]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
              state: "T"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cs2gsi
              data:
                brightness_pct: 100
                hs_color: [120, 100]

      default:
        - service: light.turn_on
          target:
            entity_id: light.cs2gsi
          data:
            brightness_pct: 100
            color_temp_kelvin: 4500

    - delay:
        milliseconds: 500

    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_led_packages
  mode: restart
